### ISSUE TITLE
Amazing rice but the top left leaf icon doesn't appear for me

### ISSUE THREAD

**Issue by d-chriss** [Manas140/Desktop-Setup#17]
As stated in the title theres no top left leaf
![image](https://github.com/Manas140/dotfiles/assets/113618049/4cdc57e8-a05c-400d-9144-1c75476449e2)

**Comment by Manas140** [comment]
Hmm, well the leaf icon is from the same font family as the system icons
`` <- try this

**Comment by d-chriss** [comment]
randomly started working, sorry for the inconvenience
